# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openlattice-rundeck
from openlattice-rundeck.models.retry_execution_request import RetryExecutionRequest  # noqa: E501
from openlattice-rundeck.rest import ApiException

class TestRetryExecutionRequest(unittest.TestCase):
    """RetryExecutionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RetryExecutionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openlattice-rundeck.models.retry_execution_request.RetryExecutionRequest()  # noqa: E501
        if include_optional :
            return RetryExecutionRequest(
                arg_string = '0', 
                loglevel = 'DEBUG', 
                as_user = '0', 
                options = None
            )
        else :
            return RetryExecutionRequest(
        )

    def testRetryExecutionRequest(self):
        """Test RetryExecutionRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
