# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openlattice-rundeck
from openlattice-rundeck.models.paging import Paging  # noqa: E501
from openlattice-rundeck.rest import ApiException

class TestPaging(unittest.TestCase):
    """Paging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Paging
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openlattice-rundeck.models.paging.Paging()  # noqa: E501
        if include_optional :
            return Paging(
                count = 56, 
                total = 56, 
                offset = 56, 
                max = 56
            )
        else :
            return Paging(
        )

    def testPaging(self):
        """Test Paging"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
