# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openlattice-rundeck
from openlattice-rundeck.api.job_api import JobApi  # noqa: E501
from openlattice-rundeck.rest import ApiException


class TestJobApi(unittest.TestCase):
    """JobApi unit test stubs"""

    def setUp(self):
        self.api = openlattice-rundeck.api.job_api.JobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api34_job_id_workflow_get(self):
        """Test case for api34_job_id_workflow_get

        Get job workflow tree.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
