# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openlattice-rundeck
from openlattice-rundeck.models.workflow_step import WorkflowStep  # noqa: E501
from openlattice-rundeck.rest import ApiException

class TestWorkflowStep(unittest.TestCase):
    """WorkflowStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WorkflowStep
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openlattice-rundeck.models.workflow_step.WorkflowStep()  # noqa: E501
        if include_optional :
            return WorkflowStep(
                jobref = None, 
                job_id = '0', 
                description = '0', 
                _exec = '0', 
                script = '0', 
                scriptfile = '0', 
                scripturl = '0', 
                type = '0', 
                node_step = '0', 
                workflow = [
                    openlattice-rundeck.models.workflow_step.WorkflowStep(
                        jobref = openlattice-rundeck.models.jobref.jobref(
                            name = '0', 
                            group = '0', 
                            uuid = '0', 
                            node_step = '0', 
                            import_options = True, ), 
                        job_id = '0', 
                        description = '0', 
                        exec = '0', 
                        script = '0', 
                        scriptfile = '0', 
                        scripturl = '0', 
                        type = '0', 
                        node_step = '0', 
                        workflow = [
                            openlattice-rundeck.models.workflow_step.WorkflowStep(
                                job_id = '0', 
                                description = '0', 
                                exec = '0', 
                                script = '0', 
                                scriptfile = '0', 
                                scripturl = '0', 
                                type = '0', 
                                node_step = '0', )
                            ], )
                    ]
            )
        else :
            return WorkflowStep(
        )

    def testWorkflowStep(self):
        """Test WorkflowStep"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
