# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openlattice-rundeck
from openlattice-rundeck.models.execution_output import ExecutionOutput  # noqa: E501
from openlattice-rundeck.rest import ApiException

class TestExecutionOutput(unittest.TestCase):
    """ExecutionOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ExecutionOutput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openlattice-rundeck.models.execution_output.ExecutionOutput()  # noqa: E501
        if include_optional :
            return ExecutionOutput(
                id = '0', 
                offset = '0', 
                completed = True, 
                exec_completed = True, 
                has_failed_nodes = True, 
                exec_state = '0', 
                last_modified = '0', 
                exec_duration = 1.337, 
                percent_loaded = 1.337, 
                total_size = 1.337, 
                retry_backoff = 1.337, 
                cluster_exec = True, 
                compacted = True, 
                entries = [
                    openlattice-rundeck.models.execution_output_entry.ExecutionOutputEntry(
                        time = '0', 
                        absolute_time = '0', 
                        log = '0', 
                        level = '0', 
                        stepctx = '0', 
                        node = '0', )
                    ]
            )
        else :
            return ExecutionOutput(
                id = '0',
                offset = '0',
                completed = True,
                exec_completed = True,
                has_failed_nodes = True,
                exec_state = '0',
                last_modified = '0',
                exec_duration = 1.337,
                percent_loaded = 1.337,
                total_size = 1.337,
                retry_backoff = 1.337,
                cluster_exec = True,
                compacted = True,
                entries = [
                    openlattice-rundeck.models.execution_output_entry.ExecutionOutputEntry(
                        time = '0', 
                        absolute_time = '0', 
                        log = '0', 
                        level = '0', 
                        stepctx = '0', 
                        node = '0', )
                    ],
        )

    def testExecutionOutput(self):
        """Test ExecutionOutput"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
