# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openlattice-rundeck
from openlattice-rundeck.models.incomplete_log_execution import IncompleteLogExecution  # noqa: E501
from openlattice-rundeck.rest import ApiException

class TestIncompleteLogExecution(unittest.TestCase):
    """IncompleteLogExecution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IncompleteLogExecution
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openlattice-rundeck.models.incomplete_log_execution.IncompleteLogExecution()  # noqa: E501
        if include_optional :
            return IncompleteLogExecution(
                id = '0', 
                project = '0', 
                href = '0', 
                permalink = '0', 
                storage = None, 
                errors = [
                    '0'
                    ]
            )
        else :
            return IncompleteLogExecution(
        )

    def testIncompleteLogExecution(self):
        """Test IncompleteLogExecution"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
