# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openlattice-rundeck.configuration import Configuration


class AclReference(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'path': 'str',
        'type': 'str',
        'name': 'str',
        'href': 'str'
    }

    attribute_map = {
        'path': 'path',
        'type': 'type',
        'name': 'name',
        'href': 'href'
    }

    def __init__(self, path=None, type=None, name=None, href=None, local_vars_configuration=None):  # noqa: E501
        """AclReference - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._path = None
        self._type = None
        self._name = None
        self._href = None
        self.discriminator = None

        if path is not None:
            self.path = path
        if type is not None:
            self.type = type
        if name is not None:
            self.name = name
        if href is not None:
            self.href = href

    @property
    def path(self):
        """Gets the path of this AclReference.  # noqa: E501


        :return: The path of this AclReference.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this AclReference.


        :param path: The path of this AclReference.  # noqa: E501
        :type path: str
        """

        self._path = path

    @property
    def type(self):
        """Gets the type of this AclReference.  # noqa: E501


        :return: The type of this AclReference.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AclReference.


        :param type: The type of this AclReference.  # noqa: E501
        :type type: str
        """

        self._type = type

    @property
    def name(self):
        """Gets the name of this AclReference.  # noqa: E501


        :return: The name of this AclReference.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AclReference.


        :param name: The name of this AclReference.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def href(self):
        """Gets the href of this AclReference.  # noqa: E501


        :return: The href of this AclReference.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this AclReference.


        :param href: The href of this AclReference.  # noqa: E501
        :type href: str
        """

        self._href = href

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AclReference):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AclReference):
            return True

        return self.to_dict() != other.to_dict()
