# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openlattice-rundeck.configuration import Configuration


class InvalidAclPolicyResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'valid': 'bool',
        'policies': 'list[InvalidAclPolicyResponsePolicies]'
    }

    attribute_map = {
        'valid': 'valid',
        'policies': 'policies'
    }

    def __init__(self, valid=None, policies=None, local_vars_configuration=None):  # noqa: E501
        """InvalidAclPolicyResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._valid = None
        self._policies = None
        self.discriminator = None

        if valid is not None:
            self.valid = valid
        if policies is not None:
            self.policies = policies

    @property
    def valid(self):
        """Gets the valid of this InvalidAclPolicyResponse.  # noqa: E501


        :return: The valid of this InvalidAclPolicyResponse.  # noqa: E501
        :rtype: bool
        """
        return self._valid

    @valid.setter
    def valid(self, valid):
        """Sets the valid of this InvalidAclPolicyResponse.


        :param valid: The valid of this InvalidAclPolicyResponse.  # noqa: E501
        :type valid: bool
        """

        self._valid = valid

    @property
    def policies(self):
        """Gets the policies of this InvalidAclPolicyResponse.  # noqa: E501


        :return: The policies of this InvalidAclPolicyResponse.  # noqa: E501
        :rtype: list[InvalidAclPolicyResponsePolicies]
        """
        return self._policies

    @policies.setter
    def policies(self, policies):
        """Sets the policies of this InvalidAclPolicyResponse.


        :param policies: The policies of this InvalidAclPolicyResponse.  # noqa: E501
        :type policies: list[InvalidAclPolicyResponsePolicies]
        """

        self._policies = policies

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InvalidAclPolicyResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InvalidAclPolicyResponse):
            return True

        return self.to_dict() != other.to_dict()
