# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openlattice-rundeck.configuration import Configuration


class JobReference(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'href': 'str',
        'permalink': 'str',
        'id': 'str',
        'pervious_owner': 'str'
    }

    attribute_map = {
        'href': 'href',
        'permalink': 'permalink',
        'id': 'id',
        'pervious_owner': 'pervious-owner'
    }

    def __init__(self, href=None, permalink=None, id=None, pervious_owner=None, local_vars_configuration=None):  # noqa: E501
        """JobReference - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._href = None
        self._permalink = None
        self._id = None
        self._pervious_owner = None
        self.discriminator = None

        if href is not None:
            self.href = href
        if permalink is not None:
            self.permalink = permalink
        if id is not None:
            self.id = id
        if pervious_owner is not None:
            self.pervious_owner = pervious_owner

    @property
    def href(self):
        """Gets the href of this JobReference.  # noqa: E501


        :return: The href of this JobReference.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this JobReference.


        :param href: The href of this JobReference.  # noqa: E501
        :type href: str
        """

        self._href = href

    @property
    def permalink(self):
        """Gets the permalink of this JobReference.  # noqa: E501


        :return: The permalink of this JobReference.  # noqa: E501
        :rtype: str
        """
        return self._permalink

    @permalink.setter
    def permalink(self, permalink):
        """Sets the permalink of this JobReference.


        :param permalink: The permalink of this JobReference.  # noqa: E501
        :type permalink: str
        """

        self._permalink = permalink

    @property
    def id(self):
        """Gets the id of this JobReference.  # noqa: E501


        :return: The id of this JobReference.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this JobReference.


        :param id: The id of this JobReference.  # noqa: E501
        :type id: str
        """

        self._id = id

    @property
    def pervious_owner(self):
        """Gets the pervious_owner of this JobReference.  # noqa: E501


        :return: The pervious_owner of this JobReference.  # noqa: E501
        :rtype: str
        """
        return self._pervious_owner

    @pervious_owner.setter
    def pervious_owner(self, pervious_owner):
        """Sets the pervious_owner of this JobReference.


        :param pervious_owner: The pervious_owner of this JobReference.  # noqa: E501
        :type pervious_owner: str
        """

        self._pervious_owner = pervious_owner

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobReference):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, JobReference):
            return True

        return self.to_dict() != other.to_dict()
