# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openlattice-rundeck.configuration import Configuration


class JobInputFileListResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'paging': 'Paging',
        'files': 'list[JobInputFileInfo]'
    }

    attribute_map = {
        'paging': 'paging',
        'files': 'files'
    }

    def __init__(self, paging=None, files=None, local_vars_configuration=None):  # noqa: E501
        """JobInputFileListResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._paging = None
        self._files = None
        self.discriminator = None

        self.paging = paging
        self.files = files

    @property
    def paging(self):
        """Gets the paging of this JobInputFileListResponse.  # noqa: E501


        :return: The paging of this JobInputFileListResponse.  # noqa: E501
        :rtype: Paging
        """
        return self._paging

    @paging.setter
    def paging(self, paging):
        """Sets the paging of this JobInputFileListResponse.


        :param paging: The paging of this JobInputFileListResponse.  # noqa: E501
        :type paging: Paging
        """
        if self.local_vars_configuration.client_side_validation and paging is None:  # noqa: E501
            raise ValueError("Invalid value for `paging`, must not be `None`")  # noqa: E501

        self._paging = paging

    @property
    def files(self):
        """Gets the files of this JobInputFileListResponse.  # noqa: E501


        :return: The files of this JobInputFileListResponse.  # noqa: E501
        :rtype: list[JobInputFileInfo]
        """
        return self._files

    @files.setter
    def files(self, files):
        """Sets the files of this JobInputFileListResponse.


        :param files: The files of this JobInputFileListResponse.  # noqa: E501
        :type files: list[JobInputFileInfo]
        """
        if self.local_vars_configuration.client_side_validation and files is None:  # noqa: E501
            raise ValueError("Invalid value for `files`, must not be `None`")  # noqa: E501

        self._files = files

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobInputFileListResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, JobInputFileListResponse):
            return True

        return self.to_dict() != other.to_dict()
