# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openlattice-rundeck.configuration import Configuration


class StorageKeyMetadata(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'meta': 'object',
        'url': 'str',
        'name': 'str',
        'type': 'str',
        'path': 'str'
    }

    attribute_map = {
        'meta': 'meta',
        'url': 'url',
        'name': 'name',
        'type': 'type',
        'path': 'path'
    }

    def __init__(self, meta=None, url=None, name=None, type=None, path=None, local_vars_configuration=None):  # noqa: E501
        """StorageKeyMetadata - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._meta = None
        self._url = None
        self._name = None
        self._type = None
        self._path = None
        self.discriminator = None

        if meta is not None:
            self.meta = meta
        if url is not None:
            self.url = url
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if path is not None:
            self.path = path

    @property
    def meta(self):
        """Gets the meta of this StorageKeyMetadata.  # noqa: E501


        :return: The meta of this StorageKeyMetadata.  # noqa: E501
        :rtype: object
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this StorageKeyMetadata.


        :param meta: The meta of this StorageKeyMetadata.  # noqa: E501
        :type meta: object
        """

        self._meta = meta

    @property
    def url(self):
        """Gets the url of this StorageKeyMetadata.  # noqa: E501


        :return: The url of this StorageKeyMetadata.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this StorageKeyMetadata.


        :param url: The url of this StorageKeyMetadata.  # noqa: E501
        :type url: str
        """

        self._url = url

    @property
    def name(self):
        """Gets the name of this StorageKeyMetadata.  # noqa: E501


        :return: The name of this StorageKeyMetadata.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this StorageKeyMetadata.


        :param name: The name of this StorageKeyMetadata.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this StorageKeyMetadata.  # noqa: E501


        :return: The type of this StorageKeyMetadata.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this StorageKeyMetadata.


        :param type: The type of this StorageKeyMetadata.  # noqa: E501
        :type type: str
        """

        self._type = type

    @property
    def path(self):
        """Gets the path of this StorageKeyMetadata.  # noqa: E501


        :return: The path of this StorageKeyMetadata.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this StorageKeyMetadata.


        :param path: The path of this StorageKeyMetadata.  # noqa: E501
        :type path: str
        """

        self._path = path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StorageKeyMetadata):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StorageKeyMetadata):
            return True

        return self.to_dict() != other.to_dict()
